planning_plugins: "pilz_industrial_motion_planner/CommandPlanner"
# The order of the elements in the adapter corresponds to the order they are processed by the motion planning pipeline.
request_adapters: "default_planner_request_adapters/FixWorkspaceBounds default_planner_request_adapters/FixStartStateBounds default_planner_request_adapters/FixStartStateCollision default_planner_request_adapters/AddTimeOptimalParameterization"
 
default_planner_config: PTP
capabilities: >-
    pilz_industrial_motion_planner/MoveGroupSequenceAction
    pilz_industrial_motion_planner/MoveGroupSequenceService